### ISSUE TITLE
ActiveJob adapter doesn't work with older Rails

### ISSUE THREAD

**Issue by texpert** [ruby-amqp/kicks#14]
Can it be made optional, please?!

I am working on a project on Rails 5.2.x, and with the merge of https://github.com/ruby-amqp/kicks/pull/12 Kicks has began impossible to use.

**Comment by simi** [comment]
Rails 5.2 is EOL for 2 years and 10 months already.

**Comment by michaelklishin** [comment]
@texpert you will have to depend on a pre-#12 commit.

**Comment by texpert** [comment]
> @texpert you will have to depend on a pre-#12 commit.

Hm, @michaelklishin, then a release should have been crafted before merging the ActiveJob adapter, so it would be the last release supporting Rails before 7.1, and Ruby < 3.0. 

Though it's not late to create it right now.

**Comment by simi** [comment]
It would make sense actually, seems not too late. Release 3.0.0 as just Sneakers + rename and deps update and start with 3.1. with AJ adapter as enhancement.

**Comment by michaelklishin** [comment]
@texpert I don't mind producing a 3.0 off of a pre-#12 tag but you have to understand that you are running a Rails version that's two majors behind and about 3 years past its EOL time. So projects like Kicks don't really have to worry about Rails 5.

**Comment by michaelklishin** [comment]
@simi let's not change the name for 3.1.0 either, that can end up being a massive can of worms.

I will produce 3.0.0 off of https://github.com/ruby-amqp/kicks/commit/40db4fb3a24036a40b177d6686676a9616a9eb73 (which has a contribution by @texpert, so that's fair) and then a `3.1.0` off of current `main`. Then we can start renaming things for… I guess 4.0.

**Comment by simi** [comment]
> @simi let's not change the name for 3.1.0 either, that can end up being a massive can of worms.
> 
> I will produce 3.0.0 off of [40db4fb](https://github.com/ruby-amqp/kicks/commit/40db4fb3a24036a40b177d6686676a9616a9eb73) (which has a contribution by @texpert, so that's fair) and then a `3.1.0` off of current `main`. Then we can start renaming things for… I guess 4.0.

Sure, I mean just the gem name.

**Comment by texpert** [comment]
> @texpert I don't mind producing a 3.0 off of a pre-#12 tag but you have to understand that you are running a Rails version that's two majors behind and about 3 years past its EOL time. So projects like Kicks don't really have to worry about Rails 5.

Well, @michaelklishin, I know quite a number of projects that, being not exactly small, doesn't sustain a steady upgrade pace. (As for my personal 4 projects on Rails, I am keeping them on the verge, updating them ASAP. But they're small and easy to update.)

So, I think keeping backwards compatibility is a very valuable thing! Developing the project without breaking changes where it is possible is the best thing developers can do for the customers in long term.

I am very impressed, for example with RabbitMQ :) We're going to upgrade one server from 3.2.4 to 4.0.2. Tested it a few weeks, and it's working like a charm! ❤️

**Comment by texpert** [comment]
Oh, and I forgot to mention the main thing - Sneakers wasn't bound to Rails, I was personally toying with PORO workers, that's why I think the ActiveJob adapter should be an opt-in.

**Comment by michaelklishin** [comment]
We can make it opt-in. But for now the plan is to ship `3.0.0` without it, branch off `3.0.x` (which @texpert may choose to adopt and maintain going forward), then ship `3.1.0` with the ActiveJob adapter and take it from there.

**Comment by simi** [comment]
> Well, michaelklishin, I know quite a number of projects that, being not exactly small, doesn't sustain a steady upgrade pace. (As for my personal 4 projects on Rails, I am keeping them on the verge, updating them ASAP. But they're small and easy to update.)

There is no excuse for using EOL version. And if you're using EOL version, don't ask for support. It is that simple. :pray:

**Comment by michaelklishin** [comment]
Upgrades of large systems can take months for reasons outside of developer control. We have made a decision that seemingly works for everyone, so let's leave this discussion at that.

**Comment by michaelklishin** [comment]
@simi what is your RubyGems account, by the way? We need to make sure you have the permissions to publish gems.

**Comment by michaelklishin** [comment]
[`3.0.0`](https://rubygems.org/gems/kicks) is out. `3.1.0` will have to wait until tomorrow.

**Comment by simi** [comment]
> @simi what is your RubyGems account, by the way? We need to make sure you have the permissions to publish gems.

https://rubygems.org/profiles/retro

**Comment by michaelklishin** [comment]
@simi I've added you as an owner for `kicks`. You should get a confirmation link, just like with GitHub org membership :)

**Comment by simi** [comment]
> @simi I've added you as an owner for `kicks`. You should get a confirmation link, just like with GitHub org membership :)

I'm in, thanks.

**Comment by michaelklishin** [comment]
`3.1.0` is out.
