### ISSUE TITLE
3.1.0 is incompatible with rails 7.1.x

### ISSUE THREAD

**Issue by anoam** [ruby-amqp/kicks#20]
The thing is `ActiveJob::QueueAdapters::AbstractAdapter` first time appears only in Rails 7.2.0.

How to reproduce:
1.
```bash
gem install rails -v 7.1.5
rails new test_kicks
cd test_kicks/
```
2. Add `gem "kicks", "3.1.0"` to Gemfile
3.
```bash
bundle install
```

4. In the rails console
```ruby
require 'sneakers'
```
rises
```
uninitialized constant ActiveJob::QueueAdapters::AbstractAdapter (NameError)

    class SneakersAdapter < ::ActiveJob::QueueAdapters::AbstractAdapter
                                                      ^^^^^^^^^^^^^^^^^
Did you mean?  AbstractController
```

**Comment by simi** [comment]
seems related to https://github.com/ruby-amqp/kicks/pull/19, we will release new version to fix this soon :pray:

**Comment by michaelklishin** [comment]
I'm going to cut a new release.

**Comment by simi** [comment]
> I'm going to cut a new release.

:muscle:

**Comment by simi** [comment]
@anoam https://github.com/ruby-amqp/kicks/pull/19#issuecomment-2452299326
